// <auto-generated />
using System;
using AspNetCoreDatabaseFirstStoredProcedureCRUD.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetCoreDatabaseFirstStoredProcedureCRUD.Migrations
{
    [DbContext(typeof(SpcoreDbContext))]
    [Migration("20260921013258_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetCoreDatabaseFirstStoredProcedureCRUD.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .IsFixedLength();

                    b.Property<decimal>("SkillBudget")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId")
                        .HasName("PK__Employee__7AD04F11662A70DD");

                    b.HasIndex("SkillId");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("AspNetCoreDatabaseFirstStoredProcedureCRUD.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("SkillId")
                        .HasName("PK__Skill__DFA09187D820A0F8");

                    b.ToTable("Skill", (string)null);
                });

            modelBuilder.Entity("AspNetCoreDatabaseFirstStoredProcedureCRUD.Models.SkillModule", b =>
                {
                    b.Property<int>("SkillModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillModuleId"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("SkillModuleId")
                        .HasName("PK__SkillMod__CDCC035FB5613FF0");

                    b.HasIndex("EmployeeId");

                    b.ToTable("SkillModule", (string)null);
                });

            modelBuilder.Entity("AspNetCoreDatabaseFirstStoredProcedureCRUD.Models.Employee", b =>
                {
                    b.HasOne("AspNetCoreDatabaseFirstStoredProcedureCRUD.Models.Skill", "Skill")
                        .WithMany("Employees")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Employee__SkillI__38996AB5");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("AspNetCoreDatabaseFirstStoredProcedureCRUD.Models.SkillModule", b =>
                {
                    b.HasOne("AspNetCoreDatabaseFirstStoredProcedureCRUD.Models.Employee", "Employee")
                        .WithMany("SkillModules")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__SkillModu__Emplo__3B75D760");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AspNetCoreDatabaseFirstStoredProcedureCRUD.Models.Employee", b =>
                {
                    b.Navigation("SkillModules");
                });

            modelBuilder.Entity("AspNetCoreDatabaseFirstStoredProcedureCRUD.Models.Skill", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
